bump up version to 0.46
beproud/bpnotify pull request #10
Opened 2018-07-27 03:18 UTC by mtb-beta

2018-07-27 03:36 UTC, afiram reviewed
重要: README.md に１行でよいので説明が欲しいです

2018-07-27 03:36 UTC, afiram commented on setup.py
> +        raise
nit's

```
raise IOError("No such file or directory:", filepath)
```
とかがよいのでは

2018-07-27 04:02 UTC, afiram commented
```
test.pypi.orgにはリリースして確認済み。
https://test.pypi.org/project/bpnotify/
```

PR付帯情報は
後で追うとき用に slackではなく PRの description に書くとよいですね

2018-07-27 04:04 UTC, mtb-beta commented
再レビューお願いします。

- 指摘事項修正しました。
- 手元でバージョンを0.46.1にしたものをtest.pypi.orgにリリースして、表示確認ずみ。（test.pypi.orgは上書きできないので）
- https://test.pypi.org/project/bpnotify/0.46.1/

2018-07-27 04:27 UTC, afiram reviewed
```
+Notification routing for Django
```

README.mdの内容が抽象的なので pipでライブラリを探している利用者が見ると

- mail?
- mobile push notification proxy?
- django signal をなんか通知するやつ?

など色々想像するけど、結局よく分からない気がします。

2018-07-27 04:27 UTC, afiram commented on setup.py
> +        raise IOError("File not found : %s" % filepath)
nit's
ここではこれでいいけど、例外処理書くときの習慣として
引数分けると例外msgをパースせずに例外内容(ファイル名とか)を取得できていいんじゃないかなーと思いました

```
In [38]: try:
    ...:     raise IOError("File not found :" ,"aa.txt")
    ...: except IOError as e:
    ...:     print(e.args)
    ...:
('File not found :', 'aa.txt')
```

2018-07-27 04:31 UTC, aodag commented on setup.py
> +        raise IOError("File not found : %s" % filepath)
これ、自分でやらなくてもファイルがないときに open すればそういうエラーになるんじゃないの

2018-07-27 04:32 UTC, aodag requested changes

2018-07-27 04:32 UTC, aodag commented on setup.py
> +        raise IOError("File not found : %s" % filepath)
この内容で例外をあげるなら exists チェックしないだけでよいです。

2018-07-27 06:07 UTC, mtb-beta commented
指摘事項を修正しました。再レビューお願いします。

- test.pypi.orgに`0.46.2` で試しにアップロード済み。 https://test.pypi.org/project/bpnotify/0.46.2/

2018-07-27 06:25 UTC, shimizukawa requested changes
バグあり

2018-07-27 06:25 UTC, shimizukawa commented on setup.py
> +    return read_text
nits
```
    with open(filepath) as f:
        return f.read()
```
で良い気もするけど、些細なことなので、これでよさそう

2018-07-27 06:25 UTC, shimizukawa commented on MANIFEST.in
> +README.md
NG 直接書くのではだめでは？
書式のドキュメントはこちら
https://docs.python.org/ja/3/distutils/sourcedist.html#specifying-the-files-to-distribute

2018-07-27 06:39 UTC, aodag commented on MANIFEST.in
> +README.md
bpmailerも確認しましょう
sdistには入ったのかな。 egg info の SOURCES.txt を確認。

2018-07-27 06:42 UTC, aodag approved these changes
nits
MANIFEST.in の確認しといてください

2018-07-27 06:58 UTC, mtb-beta commented on MANIFEST.in
> +README.md
- sdistには、README.mdが入っています。
- sdistのegg infoのSOURCES.txtにもREADME.mdが入っています。
- bpmailerも同様に入っています。
- ドキュメントを見たのですが、以下の記載を見る限り、単一のファイルを指定するときは、そのまま指定するのだと思います。

> 自分用のマニフェストファイルを書きたいなら、その形式は簡単です: 一行あたり一つの通常ファイル (または通常ファイルに対するシンボリックリンク) だけを書きます。

2018-07-27 07:20 UTC, shimizukawa commented on MANIFEST.in
> +README.md
@mtb-beta それは `MANIFEST` ファイルの話です。 `MANIFEST.in` は `MANIFEST` のテンプレートです。

2018-07-27 07:45 UTC, mtb-beta commented
MANIFEST.iniからREADME.mdを削除しました。

2018-07-27 08:02 UTC, shimizukawa reviewed
commented

2018-07-27 08:02 UTC, shimizukawa commented on MANIFEST.in
> -README.md
include README.md するべきではないか？

https://docs.python.org/ja/3/distutils/sourcedist.html には `README.txt` および `README` は自動的に同根される、とあるけれど、 `README.md` については触れられていない。

いま仕様外で `README.md` が同根されることはmtb_betaの環境ではそうかもしれないけど、他の人は違うかも知れない(setuptoolsやPythonバージョンに依存するドキュメント外の挙動）。

（あるいは、これ削って大丈夫な根拠がほしい）

2018-07-30 05:52 UTC, mtb-beta commented on MANIFEST.in
> -README.md
- setuptools36以降では `README.md` は `MANIFEST.ini` に記載せずとも同梱されるようになった。
- しかし、setuptoolsのバージョン更新が早く、現時点では古いsetuptoolsのバージョンを使っている環境もあることを考え、 `include README.md` を追記した。

2018-07-30 06:24 UTC, mtb-beta commented
再確認をお願いします。以下、前回レビュー時からの差分です。

- travis.ymlの修正を取り込みました。
- travisでのチェックでsetup.py周りでバグが見つかったので修正し、ciがpassすることを確認しました。
- README.mdはMANIFEST.inにinclude文を書くことにしました。
- 上記を踏まえて、test.pypi.orgに再アップし、表示を確認しました。 https://test.pypi.org/project/bpnotify/0.46.3/

2018-07-30 06:27 UTC, shimizukawa approved these changes
LGTM 👍

2018-07-30 06:27 UTC, shimizukawa commented on README.md
> +bpnotify is Notification routing for Django. Application notify function with targets, notify_type, media, extra_data, then bpnotify send notify with backend (example: mail).
> bpnotify is Notification ...

こまかいけど、ここは以下のようになってるとよさそう
```
`bpnotify` is notification ...
```
先頭小文字始まりが気になった（パッケージ名なので良いんだけど）のと、Notificationが大文字始まるなのが気になった。

2018-07-30 06:32 UTC, merged