Bug Fix. tox travis ci
beproud/bpnotify pull request #11
Opened 2018-07-27 09:23 UTC by mtb-beta

2018-07-27 09:50 UTC, shimizukawa commented
レビュー観点をかいてください。

今はそれが分からないので、「動いてるならいいんじゃね」ってなります

2018-07-30 00:53 UTC, mtb-beta commented
TravisでCIが実行できていなかったので実行できるように修正しました。
TravisでCIのテストが実効されることは確認していますが、明らかにおかしい修正をしていないかレビューいただきたいです。

2018-07-30 01:24 UTC, aodag requested changes

2018-07-30 01:24 UTC, aodag commented on .travis.yml
> +  - pip install tox-travis
上記では4つのケースに分類されて実行されていたのがpy36の中でdjang18,111の2つのtox env で実行されるようになりましたが意図の通りでしょうか？

2018-07-30 01:26 UTC, aodag commented on .travis.yml
> +  - pip install tox-travis
https://tox-travis.readthedocs.io/en/stable/envlist.html#advanced-configuration こちらを確認してください。

2018-07-30 02:11 UTC, aodag approved these changes

2018-07-30 02:35 UTC, mtb-beta commented on .travis.yml
> +  - pip install tox-travis
意図通りではなかったので修正しました。

2018-07-30 02:47 UTC, merged